spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: toor
    driver-class-name: com.mysql.jdbc.Driver
#  main:
#    banner-mode: off

#logging:
#  level:
#    root: warn
#    org:
#      hibernate:
#        sql=trace
#        orm.jdbc.bind=trace

