#MySQL DB connection
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gh-helper
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: toor

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
#    show-sql: true

#logging:
#  level:
#    org:
#      hibernate:
#        type: off
#      springframework:
#        security:
#          type: off

security:
  jwt:
    secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration: 86400000
    refresh-token:
      expiration: 604800000
