#MySQL DB connection
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gh-helper
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: toor

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
#    show-sql: true

#logging:
#  level:
#    org:
#      hibernate:
#        type: off
#      springframework:
#        security:
#          type: off